### ISSUE TITLE
Slap command format enhance

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/Botanist#111]
**My feature request is about**
Enhance the design/format of the command `::slap`.

**Description of the solution I'd like**
The slap command should be deleted after the embed, it's a little redundant otherwise.
Also the embed is a little big and information are redundant too (see the image below).
Last thing, the reason isn't really readable, it's hard too see why the user has been slapped. The reason should be highlighted (with a separation and/or bold).

**Additional context**
![slap redundancy](https://user-images.githubusercontent.com/23219818/80956938-b619cb80-8df1-11ea-87b4-80b9cebcafc7.png)

**What needs to be done**
- [x] Delete the command
- [x] Avoid redundancy
- [x] Highlight the reason

**Comment by s0lst1ce** [comment]
For this remember to change the way `slaps` work so that it becomes independent of `slap` behavior **and** doesn't require the command message. This is indeed an ugly implementation.

**Comment by s0lst1ce** [comment]
Done with latest commit.
