### ISSUE TITLE
[help] information sends a new embed

### ISSUE THREAD

**Issue by ahmedplat12** [s0lst1ce/Botanist#114]
An unexpected command error.

Running the ::help command and manually deleting it, then waiting for a few mins.
(it might be because of someone using the ::clear command after the help command to delete the help command's embedded message but I think it's just that it's being deleted before it deletes itself, not necessarily the ::clear command).

After a while it should post a "Command Error: Unexpected error".

I think what's happening is, since the ::help commands delete themselves after a while, if they are manually deleted before they delete themselves the bot still goes to find the embedded message it's supposed to auto delete and doesn't find it so it just prints out an error.

**Comment by s0lst1ce** [comment]
This has been resolved in a previous commit.
