### ISSUE TITLE
No logging in the rewrite branch

### ISSUE THREAD

**Issue by s0lst1ce** [s0lst1ce/Botanist#13]
Logging should be setup correctly and in a flexible way in the rewrite branch.

**Comment by adrienluitot** [comment]
What do you mean by that ? What I'm suppose to do ? ^^

**Comment by s0lst1ce** [comment]
It's what I told you today but I'll do it don't wry.

**Comment by s0lst1ce** [comment]
Fixed with https://github.com/organic-bots/ForeBot/commit/9749a82d9f10545acd1b53cf30bf0d5f71cad4e4
