### ISSUE TITLE
Command pardon count

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/Botanist#16]
It could be cool to do something like `::pardon @adrienluitot 2` to remove 2 warning, current `::pardon` removes all the warning. It's annoying if we slapped the wrong person for example.

**Comment by s0lst1ce** [comment]
I think we should still be able to clear all slaps at once. How would you prefer this to happen: no `nbr` arg would mean all or have something like a `all` parameter ?

**Comment by adrienluitot** [comment]
no `nbr` = remove all (like now)

**Comment by s0lst1ce** [comment]
Ok I'll do this ;)

**Comment by s0lst1ce** [comment]
Should we also have similar function for `slap` so that we can punish some offenses more than others ?

**Comment by s0lst1ce** [comment]
@adrienluitot re-open this issue if you want me to add something similar for `slap`.
