### ISSUE TITLE
Add a way to manually add a poll to any channel

### ISSUE THREAD

**Issue by s0lst1ce** [s0lst1ce/Botanist#2]

**Comment by s0lst1ce** [comment]
I wonder if we should really do this because it may cause issues for listeners. Or we would have to change from tracking only specific channels to also track specific messages. May be too inefficient. Awaiting your thoughts on this. Do you think it's really worth it  @organic-bots/devs ?

**Comment by adrienluitot** [comment]
I don't think, I don't really see the goal, If we really want people to see a poll there is the @everyone

**Comment by s0lst1ce** [comment]
Ok I'm closing this issue then.
