### ISSUE TITLE
Todo doesn't work

### ISSUE THREAD

**Issue by s0lst1ce** [s0lst1ce/Botanist#27]
**Describe the bug**
None of the todo commands seem to be working

**Example**
Everytime a command from the Todo suite is called nothing happens.

**Expected behavior**
The command returning something.

**Comment by adrienluitot** [comment]
Should Work with this commit : 4a0cdb39d6422f3d4c5f90e7b4a6efbe4fb0cf2e

**Comment by s0lst1ce** [comment]
It's on the test list. I'll take a look at it when I'll implement its configuration entry. This is the last step to release v0.1 !
