### ISSUE TITLE
Add a settings configuration from discord

### ISSUE THREAD

**Issue by s0lst1ce** [s0lst1ce/Botanist#4]
Add a suite of functions which allow any admin to change the way the bot works. More specifically it would allow to change settings in `settings.py`

Checklist of all that's left to do:
- [x] Poll configuration (@NotaSmartDev )
- [x] Role configuration (@NotaSmartDev )
- [x] BotEssentials configuration (@NotaSmartDev ) #30 & more
- [x] Todo configuration (@NotaSmartDev  )
- [x] Update documentation

**Comment by s0lst1ce** [comment]
To make this more powerful functions such as poll should depend not on channels' name but rather on their unique IDs. Those IDs would be logged and could be changed at any time.

**Comment by s0lst1ce** [comment]
The same accounts for roles.

**Comment by s0lst1ce** [comment]
All global setting in `settings.py` should be editable from discord

**Comment by s0lst1ce** [comment]
Should the configuration interface include all of the informations from the README.md ? @adrienluitot

**Comment by s0lst1ce** [comment]
Removed `Slapping` configuration.

**Comment by s0lst1ce** [comment]
@adrienluitot Huge question that would change everything I've done so far concerning server specific configuration... sometimes dramatic changes are required (yes I'm looking at you `rewrite`).
Anyways do you think there should be a config file for each server ? As of now there is a config file for each feature but I just thought that this may get ugly with time. I'll let you time to think about it and I'll pursue with the current structure in mind... for now. It change is needed, the hardest part will already be done.

**Comment by s0lst1ce** [comment]
This would even allow us to easily use JSON which is much more commonly understood by programmers. And it would also allow extensions to reload only specific files instead of everything each time a single modification has been done for any server.

**Comment by s0lst1ce** [comment]
We are now switching to this new configuration structure for its benefits are numerous and more important than the current one.

**Comment by s0lst1ce** [comment]
Also JSON will now be used for the configuration files. It's a common format much used among programmers and it's easy to handle in python using the `json` built-in module.
The config files will be named like this: `guild_id.json`

**Comment by adrienluitot** [comment]
I don't really know, it depends on how you want to "use" your bot. If you want to host it for other servers (not yours) I think have different config is needed. But in any case I think it could be cool if you have multiple server, for example if you have a french and an english server the "poll" channel will not have the same name.

**Comment by s0lst1ce** [comment]
There will indeed be one host (me) who will run it for several servers. I'm not sure I understand what you mean by "poll" though ? Server owners are already able to mark *any* channel as a poll one. Thus the language doesn't matter, only IDs do.

**Comment by s0lst1ce** [comment]
@adrienluitot all that's left is the Todo which I haven't looked at yet. We're almost there !

**Comment by s0lst1ce** [comment]
Finally completed with https://github.com/organic-bots/ForeBot/commit/5d59919d5471a159405f73bfe2971f0f0a2b52bf
There will be improvements for `v2` but this will be another issue's story. The same goes if new issues occur because of this.
