### ISSUE TITLE
[Remind Me in X time Function]

### ISSUE THREAD

**Issue by morcup** [s0lst1ce/Botanist#61]
**My feature request is about**
- A new feature

**Description of the solution I'd like**
I would like a remind me function to be added.  The user would input something like, "Remind me : 4 days, 3 hours," You would pick a message to be reminded of, and the bot would ping your and/or send a pm reminding you of the relevant message.

**Alternatives I've considered**
None thought of.

**Additional context**
Here is a sample of how things might happen:
:remind 01:20:12:25
THE BOT: "I'll remind you of this message in 1 days 20 hours 12 minutes and 25 seconds."
after 1 days 20 hours 12 minutes and 25 seconds(edited)
THE BOT: "Do you remember you had to check [msg link here]

**What needs to be done**
- [X ] Implement feature X
- [X ] Write documentation for feature X

**Comment by s0lst1ce** [comment]
Done with https://github.com/organic-bots/ForeBot/commit/867f99b04dabdd3ec1a50d9aa00e19499157d315
