### ISSUE TITLE
Add images to README [REQUEST]

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/Botanist#69]
**My feature request is about**
Adding pictures/images/screenshots on the README file :D

**What needs to be done**
- [ ] Implement feature

**Comment by s0lst1ce** [comment]
I'm sorry but I have trouble understanding which kind of pictures you'd want to add?
Do you mean a showcase of the bot's abilities? If so, wouldn't it be easier to depict dynamic commands' abilities through a video?

**Comment by adrienluitot** [comment]
No problem, I was thinking about the README, for some commands it would be nice to give some screenshots e.g. for Embeds because I think that some people doesn't know what is embeds.
Or for the polls to show how it looks.

**Comment by s0lst1ce** [comment]
🤔 I see. Well the README is pretty crowded with explanations as it is (thinking of the tables). We could either put them in the extension description, or restructure the documentation or make a video. Would you like to do that.
I'm thinking that moving the commands usage docs somewhere else (maybe GH pages) would be better? I have no experience in the matter.

**Comment by adrienluitot** [comment]
Yes it's true :thinking: 
We could at this the the website ;) I should work on this, let's talk about that in private ;)

**Comment by s0lst1ce** [comment]
So, shall we agree not to do this since we're going to have a website? @adrienluitot

**Comment by adrienluitot** [comment]
Seems to :smirk: 

![image](https://user-images.githubusercontent.com/23219818/68337699-5b711280-00e1-11ea-8346-8ea206e65835.png)
