### ISSUE TITLE
Add aliases to commands

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/Botanist#78]
### My feature request is about
Add aliases to commands. Like `::slap` - `::warning`, or `::help` `::h`

### Aliases requested
*These are examples that can be accepted or not !*
- [x] extension(s) [ext]
- [x] poweroff [shutdown]
- [x] warn/warning [slap]
- [x] waning**s** [slap**s**]
- [x] pardon [forgive] (keep both, because pardon is well known)
~config [cfg]~ *deprecated*

**Comment by s0lst1ce** [comment]
Ok we can do this easilly by adding the `alias` parameter to the `command` decorator

**Comment by adrienluitot** [comment]
Nice :D

**Comment by s0lst1ce** [comment]
Could you make a list you'd like to implement? Also do note that the `pardon`has been renamed `forgive`. So maybe, include this in your list ;)

**Comment by adrienluitot** [comment]
I updated the main topic with a todo list :D

**Comment by s0lst1ce** [comment]
I like all of them
