### ISSUE TITLE
mutes command

### ISSUE THREAD

**Issue by s0lst1ce** [s0lst1ce/Botanist#84]
The command you'd like
A command to view every member that his currently muted.

Additional context/ how to implement it
This could look like `slaps`. This would require to store the mutings, which is a good idea since it is **not** safe for it depends solely on the asyncio loop.

What needs to be done:
- [x] Write command
- [x] Write documentation for command

**Comment by adrienluitot** [comment]
Wouldn't it be better to use a command like `mutes` to keep the format of the slap command ?

**Comment by s0lst1ce** [comment]
You're right. I'll change the command's name. It is written just not pushed nor merged, should have it ready with the next update alongside #54
