### ISSUE TITLE
Add feature to assign role based on reaction to a post

### ISSUE THREAD

**Issue by morcup** [s0lst1ce/Botanist#92]
**My feature request is about**
- A new feature
I would like to see a way to add roles to users when they react to a post.

**Description of the solution I'd like**
The bot will assign a role based on which reaction they add to a certain post

**Alternatives I've considered**
Manually assigning roles

**Additional context**
none

**What needs to be done**
- [ ] Implement role attribution through reaction
- [ ] Document it in the `#Role` section

**Comment by s0lst1ce** [comment]
For now this will only be implemented with the event planner command.
