### ISSUE TITLE
Users can't know they've been slapped/forgiven

### ISSUE THREAD

**Issue by s0lst1ce** [s0lst1ce/Botanist#99]
**Describe the bug**
Users can't know they've been slapped/forgiven if they don't have access to the channel the command was issued. This is a big issue, especially for slapping.

**Steps to reproduce**
Slap a member that do not have access to the current channel.

**Expected behavior**
Users should know of their current moderation status in a server.

**Additional context**
A good way to fix this would be to send a copy of the message as a DM to the user if the said user does not have access  to the channel.

**Comment by s0lst1ce** [comment]
@adrienluitot what do you think is the best way to do this? A command to get your slaps in a server (or all servers). Or simply a message in DM when you get slapped? Or both? Do note that the current implementation to get the slaps is quite slow.

**Comment by adrienluitot** [comment]
Well, I think the DM is the best thing and also the easier thing to do.
We just need to precise on which server the user was slap.

**Comment by s0lst1ce** [comment]
ofc, this is simple enough though. I'll write something for this. Maybe I should remove the in-server message altogether? It takes a lot of visual space afterall.

**Comment by adrienluitot** [comment]
I guess a message on the server is still important, we should just minimize the message on the server to make it less like a boat! :stuck_out_tongue:

**Comment by s0lst1ce** [comment]
Smart, I'll try and tweak it.

**Comment by s0lst1ce** [comment]
This was fixed alongside #111
